### ISSUE TITLE
translate pruning zones to calendar months

### ISSUE THREAD

**Issue by emillipede** [Public-Tree-Map/public-tree-map-data-pipeline#53]
part of #38 

SM public works breaks the city into numbered pruning zones. the numbered pruning zones correspond to thirds of the year - each zone is pruned in a defined 3 month period. 

we can specify "Pruning scheduled for May - June 2020" rather than documenting the pruning schedule as: "Pruning Year: 2019-2020, Pruning Zone: 3"

eg. for the pruning year 2019-2020, the three zones would be:

July - October 2019
November 2019 - February 2020
March - June 2020

**Comment by captainrandom** [comment]
@emillipede I have no clue what this means. Could you help me with this?
