### ISSUE TITLE
flag new species

### ISSUE THREAD

**Issue by emillipede** [Public-Tree-Map/public-tree-map-data-pipeline#56]
set up a flag/alert when a new species is added to the city [trees inventory](https://data.smgov.net/Public-Assets/Trees-Inventory/w8ue-6cnd) dataset (and isn't represented in species attributes csv)

(see #36 for other issues related to the species ID and #54 for details about what fields are documented in the species attributes csv)

- most of this issue's addressed by #82 but we still need to sort out the workflow and print just each species ID (not every instance of that species ID, for example if the arborists plant 18 tress of the same new species)

**Comment by captainrandom** [comment]
It looks like this was finished. Feel free to re-open if you needed something else.
