### ISSUE TITLE
investigate download-images.js

### ISSUE THREAD

**Issue by emillipede** [Public-Tree-Map/public-tree-map-data-pipeline#63]
**AS A/AN**:
user

**WHEN I**:
view tree details

**I WANT TO**:
whenever possible, see an image

in at least [one case](https://public-tree-map.surge.sh/?id=10936481), it seems that even though an EOL image exists for the species, and the EOL ID is documented in [species_attributes.csv](https://github.com/Public-Tree-Map/public-tree-map-data-pipeline/blob/master/data/species_attributes.csv), a tree's json file doesn't include an image

for updates to this file, I'd like to consider additional image sources: 
- [selectree](https://selectree.calpoly.edu/) 
- [iNaturalist](https://www.inaturalist.org/pages/developers)

**Comment by mrtmrt233** [comment]
Turns out this is a front end bug lol
