### ISSUE TITLE
add docker documentation

### ISSUE THREAD

**Issue by emillipede** [Public-Tree-Map/public-tree-map-data-pipeline#74]
add instructions for linux/windows docker users (shell scripts?)

add information about how to create access token?

log into docker daemon locally?

how to locally test work with circle ci and with google cloud?

add link to https://hub.docker.com/orgs/publictreemap

unit tests?

(see #69, #75)

**Comment by captainrandom** [comment]
Need to add documntation on how to:
* build
* push
* how dockerhub relates to the build


I also need to refactor a lot of these scripts.

**Comment by captainrandom** [comment]
document build-proj from the makefile

**Comment by captainrandom** [comment]
This is done in the test-circleci branch and is ready to go as part of the #69 PR.
