### ISSUE TITLE
convert node files to python

### ISSUE THREAD

**Issue by emillipede** [Public-Tree-Map/public-tree-map-data-pipeline#84]
**AS A/AN**:
new contributor

**WHEN I**:
join the project or make a contribution

**I WANT TO**:
use one language and or streamline future work

we'd like to switch the current node files to python
- [parse-trees.js](https://github.com/Public-Tree-Map/public-tree-map-data-pipeline/blob/a62e9618cb78af3bf2ddd4d7f65f869e1f9e5269/parse-trees.js)
- [download-images.js](https://github.com/Public-Tree-Map/public-tree-map-data-pipeline/blob/master/download-images.js) (please also see #63 for a possible bug in this file)
- [split-trees.js ](https://github.com/Public-Tree-Map/public-tree-map-data-pipeline/blob/a62e9618cb78af3bf2ddd4d7f65f869e1f9e5269/split-trees.js)

@isabelle-wagenvoord let me know if you'd like to look at any of the files

**Comment by nowfred** [comment]
Hello I would like to help with this

**Comment by emillipede** [comment]
@captainrandom is working on [parse-trees.js](https://github.com/Public-Tree-Map/public-tree-map-data-pipeline/blob/a62e9618cb78af3bf2ddd4d7f65f869e1f9e5269/parse-trees.js)
